apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: stable
apiServerCertSANs:
- 102.133.132.99
controlPlaneEndpoint: "102.133.132.99:6443"
etcd:
  external:
    endpoints:
    - https://110.0.2.5:2379
    - https://10.0.2.7:2379
    caFile: /etc/etcd/ca.pem
    certFile: /etc/etcd/kubernetes.pem
    keyFile: /etc/etcd/kubernetes-key.pem
networking:
  podSubnet: 192.168.0.0/16
apiServerExtraArgs:
  apiserver-count: "2"